default: &default
  client_id: <%= ENV.fetch("AUTH0_CLIENT_ID") %>
  client_secret: <%= ENV.fetch("AUTH0_CLIENT_SECRET") %>
  issuer_domain: <%= ENV.fetch("AUTH0_DOMAIN") %>
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
