default: &default
  client_id: <%= Rails.env.production? ? Rails.application.credentials.auth0_client_id : ENV.fetch("AUTH0_CLIENT_ID") %>
  client_secret: <%= Rails.env.production? ? Rails.application.credentials.auth0_client_secret : ENV.fetch("AUTH0_CLIENT_SECRET") %>
  issuer_domain: <%= Rails.env.production? ? Rails.application.credentials.auth0_domain : ENV.fetch("AUTH0_DOMAIN") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
