default: &default
  client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  issuer_domain: <%= ENV["AUTH0_DOMAIN"] %>

development:
  <<: *default

test:
  <<: *default

production:
  client_id: <%= Rails.application.credentials.dig(:auth0_client_id) %>
  client_secret: <%= Rails.application.credentials.dig(:auth0_client_secret) %>
  issuer_domain: <%= Rails.application.credentials.dig(:auth0_domain) %>
