default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || 20 %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default
  database: pairings_api_development

test:
  <<: *default
  database: pairings_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: pairings_api_production
