inherit_from:
  - .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  Exclude:
    - '**/*.erb'

Rails/ApplicationController:
  Exclude:
    - app/controllers/auth0_controller.rb
    - app/controllers/web/base_controller.rb

Naming/VariableNumber:
  AllowedIdentifiers:
    - item1
    - item2

Metrics/MethodLength:
  CountAsOne:
    - array

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3
