inherit_from:
  - .rubocop_todo.yml

inherit_gem:
  rubocop-pave:
    - default.yml

RSpecRails/InferredSpecType:
  Enabled: false

Rails/ApplicationController:
  Exclude:
    - app/controllers/auth0_controller.rb
    - app/controllers/web/base_controller.rb

Naming/VariableNumber:
  AllowedIdentifiers:
    - item1
    - item2
