name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: pairings-api/.ruby-version
          bundler-cache: true
          working-directory: ./pairings-api

      - name: Scan for common Rails security vulnerabilities using static analysis
        working-directory: ./pairings-api
        run: bundle exec brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: pairings-api/.ruby-version
          bundler-cache: true
          working-directory: ./pairings-api

      - name: Lint code for consistent style
        working-directory: ./pairings-api
        run: bundle exec rubocop -f github

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git pkg-config

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: pairings-api/.ruby-version
          bundler-cache: true
          working-directory: ./pairings-api

      - name: Run tests
        env:
          RAILS_ENV: test
          # REDIS_URL: redis://localhost:6379/0
        working-directory: ./pairings-api
        run: |
          bundle exec rails db:test:prepare
          bundle exec rspec
